version: 2.1
jobs:
  e2e:
    machine:
      image: ubuntu-2004:2023.10.1
    steps:
      - checkout
      - run:
          name: End-to-end tests
          command: |
            cd e2e
            docker-compose up --exit-code-from cypress
      - store_artifacts:
          path: e2e/cypress/videos
      - store_artifacts:
          path: e2e/cypress/screenshots
workflows:
  test:
    jobs:
      - e2e
