version: '3.2'
services:
  sentimentalyzer:
    build: ../front
    environment:
      - PORT=3000
  cypress:
    image: "cypress/included:3.7.0"
    depends_on:
      - sentimentalyzer
    environment:
      - CYPRESS_baseUrl=http://sentimentalyzer:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
